### PR TITLE
Update About page

### PR DESCRIPTION
**Pull request by jessesquires**
@stationaery, per your suggestions. How's this?

I don't think we need to mention a bunch of specific dates, circumstances, etc.

### Preview

Screen Shot 2021-01-06 at 12 26 52 PM

### CODE REVIEW

**Comment by jessesquires** [comment]
@beccalew -- I'm linking to your Twitter on the about page. (This is what the rest of us do.) Just want to make sure you are ok with this.

@kaylensanders -- Would you like your name on the "About" page linked to anything? Personal website, social media, etc.

**Comment by stationaery** [comment]
Looking good! Apologies, I forgot to name @atav1k [Vikram R](https://twitter.com/atav1k) as one of the current contributors.

**Comment by jessesquires** [comment]
oops! my bad.

**Comment by jessesquires** [comment]
updated.

@atav1k I'm assuming you are ok with linking to your twitter here? let me know.

**Review by stationaery — APPROVED** [review]
LGTM! Approved! 

Just waiting for @kaylensanders and @atav1k confirm what online presence to link to, if any, but now rush

**Comment by kaylensanders** [comment]
@jessesquires -- as of now, I'm cool with not having my name linked to an online presence since I don't have a personal website or any socials that make sense. thanks!

**Comment by stationaery** [comment]
@kaylensanders does it make sense to link to your contribution in issue 4?

**Comment by beccalew** [comment]
> @beccalew -- I'm linking to your Twitter on the about page. (This is what the rest of us do.) Just want to make sure you are ok with this.
> 
> @kaylensanders -- Would you like your name on the "About" page linked to anything? Personal website, social media, etc.

Sorry for delay - @jessesquires yes that's fine to include!

**Comment by kaylensanders** [comment]
> @kaylensanders does it make sense to link to your contribution in issue 4?

@stationaery - good idea! I'm cool with that! (also @jessesquires)

**Comment by jessesquires** [comment]
All updates made. Just waiting on @atav1k to confirm linking to twitter is good. 😊

**Comment by atav1k** [comment]
i'm good with the twitter linking and name!

**Comment by jessesquires** [comment]
link checker was upset about relative links, which are fine in this case

**Pull request merged**
