### PR TITLE
Import legacy newsletter issues as "Volume 1"

### PR DESCRIPTION
**Pull request by anaulin**
This PR adds the old issues of the TWC newsletter, imported from the Mailchimp archive at https://us11.campaign-archive.com/home/?u=194e57c175176cfd13007a197&id=7cb85d276a

I include the script that I used for the scraping, as reference. Because the issues aren't consistently formatted and because the HTML in the Mailchimp archive is not very clean, I additionally did some manual tweaking of the results of the scraper.

This resolves https://github.com/techworkersco/techworkersco.github.io/issues/5 .

Some of the legacy issues contained more than one image, and in those cases the additional images are missing (although that is typically not noticeable, as they are additional illustrations). I might return to this in the next couple of days and add those extra images.

In the meantime, this is ready for a final look @jessesquires and whoever else wants to lend a second pair of eyes or has suggestions to improve this.

### CODE REVIEW

**Comment by jessesquires** [comment]
Looks like the site builds fine, but danger is borked. I'll look into that.

**Comment by jessesquires** [comment]
ok. fixed danger and improved the CI setup in #15

**Comment by jessesquires** [comment]
pushed a minor commit here to re-trigger CI 😄

**Comment by jessesquires** [comment]
oh derp. need to rebase this for the danger changes to work. 

meh. it should be fine.

**Comment by anaulin** [comment]
FYI @jessesquires I rebased this on `master`, but the Danger run still failed. Failure logs here: https://github.com/techworkersco/techworkersco.github.io/pull/14/checks?check_run_id=583925339

I'm going to merge this now, since the site builds and the Danger failures seem to be unrelated to my changes.

**Comment by jessesquires** [comment]
@anaulin hm... very strange. 🤷‍♂️ 

if it doesn't work when we publish our first issue, i'll take another look

**Pull request merged**
