### PR TITLE
Issue 16

### PR DESCRIPTION
**Pull request by jessesquires**

### CODE REVIEW

**Comment by dellsystem** [comment]
Copied over from the draft! I changed the h3s to blockquotes because the h3s looked massive on my screen.

Also, @jessesquires I wasn't sure if this should be volume 3 (per your recent PR) or still volume 2? If it's volume 3, would we want to number it from 1 again?

**Comment by dellsystem** [comment]
screencapture-localhost-4000-2021-01-01-issue-16-2021-01-01-01_26_08

**Review by stationaery — APPROVED** [review]
Moved images, edited a few words. LGTM : ]

**Review by stationaery — APPROVED** [review]
Links fixed (I hope)

**Pull request merged**
