### PR TITLE
Testing auto-publish [do not merge manually]

### LINKED ISSUE #192: Fix auto-publish workflow
This is currently not working.

Example: https://github.com/techworkersco/techworkersco.github.io/pull/187

Filed an issue on the action repo:
https://github.com/reitermarkus/automerge/issues/272

---

~~Maybe switch to one of these instead?~~
- ~~https://github.com/marketplace/actions/automatically-merge-pr~~
- ~~https://github.com/marketplace/actions/pr-merge-bot~~

EDIT: actually these actions won't work. they can't run as cron jobs. 😭

### PR DESCRIPTION
**Pull request by jessesquires**
This is a test for `auto-publish` label.

If it is working correctly, the bot should auto-merge tomorrow morning. 🤞🏼

#### Criteria required:

- [x] All automated checks have passed 
- [x] Reviewed and Approved
- [x] Has `auto-publish` label 

closes #192

### CODE REVIEW

**Review by stationaery — APPROVED** [review]
I have almost no idea what I'm looking at, but,... lgtm!

**Comment by jessesquires** [comment]
@stationaery lol. I've just added an empty line to the `README`. We just need some change in order to test. 😊

**Comment by jessesquires** [comment]
If this doesn't work, I'll try using one of these instead:

- https://github.com/marketplace/actions/auto-pull-request-merge
- https://github.com/marketplace/actions/automatically-merge-pr

**Review by stationaery — APPROVED** [review]
🔍🧐

**Review by reitermarkus — APPROVED** [review]

**Comment by jessesquires** [comment]
it works! 🎉

**Pull request merged**
