### PR TITLE
Update call-for-submissions.md

### PR DESCRIPTION
**Pull request by stationaery**
Reduced the text by a whopping ~70% to focus on the core elements that have helped us collaborate and work with contributors over the past year

### CODE REVIEW

**Review by jessesquires — APPROVED** [review]
@stationaery looks good to me!

**Comment by jessesquires** [comment]
@stationaery Also -- I want to call out a new feature: 

See the comment by the `netlify` bot 🤖 — it contains a link with a preview of the site with the changes in the PR. That means no more guessing what changes will look like, or having to build the site locally. 😄

**Comment by stationaery** [comment]
@jessesquires I definitely made use of it! Very awesome to have that
available. (Oddly but not surprisingly the link goes to the main page vs
the page in the PR but it’s all good :)

**Comment by jessesquires** [comment]
@stationaery Ah, that's because it's a preview of the entire site rebuilt 😊

**Pull request merged**
