### PR TITLE
Vol 3 issue 15

### PR DESCRIPTION
**Pull request by dellsystem**
I went with Tamara's suggestion of "When Big Brother is your Boss", and the second image idea! Did some very basic fact-checking (mostly just spelling) and made some minor edits for flow and clarity. See the screenshot below.

screencapture-localhost-4000-2021-07-05-22_56_19

### CODE REVIEW

**Comment by dellsystem** [comment]
sorry i think i broke our workflow by using a different branch!!

**Review by stationaery — APPROVED** [review]
lgtm

**Comment by stationaery** [comment]
@jessesquires our old friends Link Checker and Danger both failed, @dellsystem and I don't know how to override them : (... please fix if you get time in the AM?

**Comment by jessesquires** [comment]
Issue 1: danger commented with instructions

We just needed to add `image-optimized` to tell danger than images we optimized.

Screen Shot 2021-07-06 at 9 36 53 AM

**Comment by jessesquires** [comment]
Issue 2: the link checker got confused

The links for the images are quoted, we can omit the quotes. 😊 

From [the logs](https://github.com/techworkersco/techworkersco.github.io/pull/237/checks?check_run_id=2996077142):

Screen Shot 2021-07-06 at 9 38 13 AM

`&quot;` is `"`

the link checker really shouldn't do this -- it's a bug.

**Comment by jessesquires** [comment]
RE: Links

oh, lol. well i guess we do have to quote the links, otherwise its a syntax error. haha. i tried using single quote instead `'`

**Review by jessesquires — APPROVED** [review]

**Comment by jessesquires** [comment]
Last issue: someone just needed to approve

**Comment by jessesquires** [comment]
I made the link checker **not** required to merge, since we've had a few instances of false positives. (because of quoting.)

If it fails, it will still show an ❌ but you can now merge anyway. 

If it does fail, then we should check the logs to make sure that the failures are, in fact, false positives.

**Comment by jessesquires** [comment]
and now i see in the commit log that @dellsystem also tried to fix the links. lol 😆 sorry folks.

**Comment by jessesquires** [comment]
I filed an issue with the link checker: https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/110

Not sure how well that project is maintained.

**Pull request merged**
