### PR TITLE
Related to issue #279. Set environment variable in netlify contexts

### PR DESCRIPTION
**Pull request by shushugah**
See https://docs.netlify.com/site-deploys/overview/#deploy-contexts

### CODE REVIEW

**Comment by shushugah** [comment]
Currently https://twc-newsletter.netlify.app/ is what's serving the news.techworkerscoalition.org which explains the missing jekyll environment being set. If this feature looks okay, we can merge this. https://twc-newsletter.netlify.app/feed.xml has same issue.

**Comment by shushugah** [comment]
FYI the linter error is unrelated, I triggered it on an empty copy of master too #283, we can safely ignore it in this case and figure that out separately

**Review by jessesquires — APPROVED** [review]

**Comment by jessesquires** [comment]
> Currently https://twc-newsletter.netlify.app/ is what's serving the news.techworkerscoalition.org which explains the missing jekyll environment being set. If this feature looks okay, we can merge this.

Ah! That explains everything.

So, to be clear, GHPages is no longer hosting `news.techworkerscoalition.org` ?

**Comment by jessesquires** [comment]
thanks @shushugah !

**Comment by jessesquires** [comment]
Just confirmed that `news.techworkerscoalition.org` is now correctly using absolute URLs for images.

Images in emails should be fixed now. 

For posterity, linking #265 here.

cc @stationaery

**Comment by jessesquires** [comment]
Oh @shushugah -- one other thing that's relevant here.

By default, Jekyll will **not** render posts with dates in the future. This means that we actually can't see previews of the upcoming issue. (For example, see #280 right now.) Only on the day of publishing can we see the preview, which requires re-trigger the workflow on that day.

Is it possible to have the Netlify previews pass `--future` to `jekyll build` for only PRs?

**Comment by shushugah** [comment]
Exactly yes! Netlify recognizes it's a jekyll file, so it has its own default build commands, but you could specify/customize your jekyll commands here underneath the non production onces, so that both branch/deploy-previews have a `jekyll build --future` config instead of `jekyll build`. Another thing perhaps worth noting that's flexible compared to github pages, is that netlify does not restrict the gems/plugins, so you can easily run any 3rd party plugins you find.

techworkersco.github.io still exists, in case you need/rely on it for anything, but I moved to netlify infrastructure for streamlined simplicity. Let me know if you want Netlify access. We have an open source plan, so unlimited number of seats. If so, share the email associated with your github.

**Comment by shushugah** [comment]
Not tested, because I'm gonna sleep but something like this I THINK? would work; would be easily testable with a PR anyhow. Note how I leave production alone, but changed the other two environments? 

```toml
# Production context:
# All deploys from the main repository branch
# will inherit these settings.
[context.production]
  [context.production.environment]
    JEKYLL_ENV = "production"

# Deploy Preview context:
# All deploys generated from a pull/merge request
# will inherit these settings.
[context.deploy-preview.environment]
  JEKYLL_ENV = "development"
  command = "jekyll build --future"


# Branch deploy context:
# All deploys that are not from a pull/merge request
# or from the production branch will inherit these settings.
[context.branch-deploy]
  JEKYLL_ENV = "development"
  command = "jekyll build --future"
```

**Comment by jessesquires** [comment]
thanks @shushugah ! 🙌🏼

**Pull request merged**
