### PR TITLE
Call for submissions page + editorial guidelines

### LINKED ISSUE #55: Create an editorial vision/process doc
Per our discussion during the May 5 meeting.

@stationaery I think you volunteered to do this, as well? If not feel free to re-assign, or we can discuss later.

#### Meeting notes

> Editorial process
>
> We need two separate docs:
> 1. editorial process, steps and schedule
> 1. editorial direction with a) political analysis on the industry without potential faux-pas, and b) commentary on our own efforts as a newsletter
>
> Host these docs in GH to enable conversation about them both

### PR DESCRIPTION
**Pull request by jessesquires**
Ok folks, here we go.

###  "call for submissions"

 Submissions content was copied from the google doc and formatted. I made some _minor_ edits. 

I feel like this needed some styling/markup to breakup the content in a way that makes it more digestible. Totally open to ideas here.

### editorial guidelines

This is the bottom section from the google doc under *"The text below seems too much for including anywhere on the website"*

I think it made the most sense to add this to our existing `CONTRIBUTING.md` doc, which is also linked from the README in the repo. This is public, and thus easily sharable with contributors.

closes #55

Here's how it looks:

Call For Submissions · TWC Newsletter

### CODE REVIEW

**Comment by stationaery** [comment]
@jessesquires I think the submit page is good to go! I do want to see what the alert box looks like on a few screens, maybe the grey background might be changed up for something else.

Also, I really don't think the 'editorial' content fits in the README.md. Maybe it can go elsewhere- perhaps in another page off of the call for submissions page, or maybe nowhere at all (it doesn't really say too much, after all).

However, I do think a link to the submissions page makes sense on the README.md -- right below About and above Documentation. Thoughts?

**Comment by anaulin** [comment]
I'm laptopless and won't look at this until the weekend, so don't block on
my review or response.

**Comment by jessesquires** [comment]
> Also, I really don't think the 'editorial' content fits in the README.md. 

it wasn't in the main README

> Maybe it can go elsewhere- perhaps in another page off of the call for submissions page, 

it was -- the contributing guide is just a doc in the repo. it is only **linked** from the README.

i still think the contributing doc makes the most sense. but we could also make a new `EDITORIAL.md` doc to put in the repo. 

> or maybe nowhere at all (it doesn't really say too much, after all).

it seems worth having somewhere -- to easily share with contributors as a reference, and generally to keep track of.

**Comment by jessesquires** [comment]
- Fixed some markdown/markup issues
- Fixed a few typos. 
- Also, specifically `200-1,200` is hard for me to parse. To me it looks like `200-1` comma `200`. 🤷  Instead, I made it `200 to 1,200`
- Minor edits to the opening line. "*some other* worker" sounded bad too me.
- I improved the "alert box" at the top. I agree it was too dark. Here's a new screenshot:

Call for Submissions · TWC Newsletter

**Comment by stationaery** [comment]
I was confused by the format of these md files coming all at once! 😬 So,
thank you for clarifying! 😁I will get going on a more narrative style
guide for the EDITORIAL.md file.

Good edits and formatting, too. The highlighting made me think we're in a
Google Doc reviewing a file that's not complete because it has comments all
over it, so I tried applying it to just a few lines to see if that help
focus more than distract.

**Pull request merged**
