### PR TITLE
Issue #5

### PR DESCRIPTION
**Pull request by jessesquires**
Just adding the empty template for now.

### CODE REVIEW

**Comment by dellsystem** [comment]
I can't believe it's only issue 5! It kind of feels like we've been doing this forever.

image

**Comment by dellsystem** [comment]
feel free to make further edits if needed. thanks for your work on this @jessesquires!

**Comment by stationaery** [comment]
Two things:

Playing forward Ana’s comment in the Paper doc: “Shut it down” as a title
doesn’t quite connect with Rohit’s piece. (And maybe we want to save that
one for later?) How about something like “Leaving the bubble for Texas?”

Also, to avoid ambiguity and give credit for the Workers Perspective, we
should insert “By R.K. Upadhya” below the header with a line break and in
bold text (similar to how we credited individuals in issue 4)

**Comment by stationaery** [comment]
Whoops- that should have been, “Leaving the bubble for Texas”? (not “Leaving the bubble for Texas?”)

**Comment by dellsystem** [comment]
LGTM! thanks @stationaery and @jessesquires

**Comment by jessesquires** [comment]
ok i think we're good to go!

**Pull request merged**
