### PR TITLE
Add basic pagination to post.html

### PR DESCRIPTION
**Pull request by dellsystem**
For issue #51. It looks really basic right now, so if you have an idea to make it nicer, go right ahead!

(Side note: how do we want to deal with the fact that volume 2 starts with issue 1? Is it confusing that the "previous issue" for issue 1 has a higher number? Do we want to include "Vol 1/2" somewhere in the link text?)

### CODE REVIEW

**Comment by jessesquires** [comment]
> It looks really basic right now, so if you have an idea to make it nicer, go right ahead!

can you post a screenshot?

**Comment by jessesquires** [comment]
> (Side note: how do we want to deal with the fact that volume 2 starts with issue 1? Is it confusing that the "previous issue" for issue 1 has a higher number? Do we want to include "Vol 1/2" somewhere in the link text?)

What if we omit the issue names and just say "Previous Issue" and "Next Issue" ?

**Comment by jessesquires** [comment]
Also, RE: making this prettier

Bootstrap has a good component for this:

https://getbootstrap.com/docs/4.4/components/pagination/

**Comment by dellsystem** [comment]
screenshots of the top of the page, and the bottom:
image
image

**Comment by dellsystem** [comment]
I did look into the pagination feature but it didn't look quite the way I wanted (pagination typically works best with a list of numbers, rather than merely next/previous). I'll mock up some options for "previous issue / next issue" though

**Comment by jessesquires** [comment]
👍 

swift weekly does this, if you need inspiration:

Screen Shot 2020-05-04 at 10 29 39 AM

**Comment by dellsystem** [comment]
I basically copied the Swift Weekly format - how does this look?

image
(mobile)

image
(desktop)

**Comment by jessesquires** [comment]
Looks great! 💯 🎉 

To me, it feels a bit weird at the top, but I don't have super strong feelings about that.

**Comment by stationaery** [comment]
I saw the < prev and next > arrows and thought, OK, makes sense, a bit
early thought ... and then saw the Twitter and FB icons and thought Hmm,
where will those take me- to the tweet or post for this issue? to share
this page? And what about sharing via email? These icons feel out of place.

Overall, I think nav and sharing interaction ought to go in the bottom of
the page (after people read the posts), not the top (before they even
decide if they like it).

**Comment by dellsystem** [comment]
fair points @stationaery @jessesquires - I can remove the navbars from the top of the page (I had them in both places for convenience's sake)

@stationaery I see what you're saying re: the Twitter/FB icons being confusing. I worried about that too. What about splitting it up unto two lines? Like
image
(the twitter/fb buttons could also just be icons, without the "Share to/Post to" text)

**Comment by stationaery** [comment]
The nav looks good to me! On the page for the most recent issue, what
happens to the 'next' button

Also, the sharing buttons look good to me! I think it might help to add a
button to share via email, or at least 'copy link to this post'

**Comment by dellsystem** [comment]
the next button simply vanishes when there is no next issue:
image

i'll add the email button now!

**Comment by jessesquires** [comment]
@dellsystem @stationaery 

What if we left the share icons in-line with the prev/next buttons, but added the text next to the icons, like:

`< Previous | Tweet | Share | Next >`

**Comment by dellsystem** [comment]
Just mocked up a few options based on the feedback above:

here's what it would look like with two lines, including email: 
image

and one line, with text next to icons, and email button:

image

the problem with the above is that it's too wide for mobile:
image

and it's still too wide even if we remove email:
image

Personally I'm partial to the two line option, since that's easier to make work for mobile. @jessesquires how would you feel about that?

**Comment by jessesquires** [comment]
the two line option looks good to me! 💯 

Having the text on the share options for the 2-line version might balance it better.

**Comment by stationaery** [comment]
Now we can say we have our own 🎉 Second Line
<https://en.wikipedia.org/wiki/Second_line_(parades)> 🎺✨

I think the prev/next text ought to go below the share line to stick with
the logic of "This issue is good ! I want to share it... OK, now on the
next issue" VS "OK, on to the next issue! I would share that last one hmm
whoops too late already on a new page."

And as for icons + text, how about a one-word prompt and icon, like this:
[tweet t][post f][email ✉️][copy 🔗]

**Comment by dellsystem** [comment]
So the problem with having 4 different buttons with icons is that it'll be too wide for some mobile clients:
image

Also, I'm having trouble getting the email link to work properly - just setting up a desktop email client has been a nightmare. So I'm inclined to drop the email button and replace it with a "copy URL" button.

How's this?
mobile:
image

desktop:
image

**Comment by jessesquires** [comment]
@dellsystem sounds good to me!

I think it might look better with the icons coming before the text.

**Pull request merged**
