### PR TITLE
Add vol 2 issue 4

### PR DESCRIPTION
**Pull request by dellsystem**
image

### CODE REVIEW

**Comment by dellsystem** [comment]
updated caption (mobile view)
image

**Comment by dellsystem** [comment]
image

**Comment by anaulin** [comment]
Thanks for putting up this last-minute PR after midnight, @dellsystem . 🙏

**Comment by stationaery** [comment]
Thank you @dellsystem for the teamwork to edit and publish this thing.
@anaulin many thanks to you for the critically important comments, too. And
thank you @jessesquires for setting boundaries this week and also weighing
in on key items along the way.

**Pull request merged**
