### PR TITLE
Issue 4 edits

### PR DESCRIPTION
**Pull request by dellsystem**
fixed caption, added spacing between worker perspectives
image

### CODE REVIEW

**Comment by jessesquires** [comment]
I think unicode "smart quotes" confuse the spellchecker

**Comment by stationaery** [comment]
Curious.. Does that have to do with text being copied over from other docs
with formatting? " VS ”?

**Comment by anaulin** [comment]
> Curious.. Does that have to do with text being copied over from other docs
with formatting? " VS ”?

Yep, that's almost certainly it. (Because people don't usually go around typing in fancy-quotes.)

**Comment by anaulin** [comment]
I wonder if we should have some pre-commit hooks or some other automation to do things like e.g. replace smart-quotes with normal-person-quotes (and whatever else we find in the future that keeps getting in the way). (The thing I don't love about hooks is that folks have to install them in their own environment, which is a tiny bit of extra setup for everyone who works with the repo.)

**Pull request merged**
