### PR TITLE
Update 2021-01-14-issue-2.md

### PR DESCRIPTION
**Pull request by stationaery**
edits to excerpt (over $205m, not $200) and header styling

### CODE REVIEW

**Comment by jessesquires** [comment]
> edits to excerpt (over $205m, not $200) and header styling

there are lots of other edits here. are those intended?

---

also -- i don't think the header looks super great that large.

note: the markdown that github renders != the styling for our site. an `h3` is much bigger than you think if you are basing this off of github markdown.

**Comment by jessesquires** [comment]
and, how critical are these changes?

i feel like we should try to avoid post-publish editing unless there's a typo or serious misinformation.

we've been doing this a lot (just in general) after emails are already sent 😞 and i think we should try to avoid it...

**Comment by stationaery** [comment]
Good question! I'd say the "over $205m" number correction is pretty
important, especially since it's repeated below. Other edits as well,
because they came out of final edits from the group of coauthors who wanted
a few more tweaks.

We can nix the header change.

And I can commit to avoiding future post-publish commits.

**Review by dellsystem — APPROVED** [review]

**Comment by dellsystem** [comment]
The changes look fine to me! I'm with Jesse on avoiding post-publish edits in general but I'm ok with it for this issue since it was a special issue with a short turnaround time.

**Comment by stationaery** [comment]
Sorry again, I accidentally changed the header style. @jessesquires feel free to change it back if you feel it looks not-great.

**Comment by jessesquires** [comment]
all good!

**Pull request merged**
